In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error
import seaborn as sns
from statsmodels.tsa import ar_model
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
import numpy as np
%matplotlib inline
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import LSTM
from keras.callbacks import EarlyStopping
from keras.layers import Dropout, TimeDistributed, RepeatVector

In [2]:
df = pd.read_csv('temp.csv')

In [3]:
df

            Date  Temp
0     1981-01-01  20.7
1     1981-01-02  17.9
2     1981-01-03  18.8
3     1981-01-04  14.6
4     1981-01-05  15.8
5     1981-01-06  15.8
6     1981-01-07  15.8
7     1981-01-08  17.4
8     1981-01-09  21.8
9     1981-01-10  20.0
10    1981-01-11  16.2
11    1981-01-12  13.3
12    1981-01-13  16.7
13    1981-01-14  21.5
14    1981-01-15  25.0
15    1981-01-16  20.7
16    1981-01-17  20.6
17    1981-01-18  24.8
18    1981-01-19  17.7
19    1981-01-20  15.5
20    1981-01-21  18.2
21    1981-01-22  12.1
22    1981-01-23  14.4
23    1981-01-24  16.0
24    1981-01-25  16.5
25    1981-01-26  18.7
26    1981-01-27  19.4
27    1981-01-28  17.2
28    1981-01-29  15.5
29    1981-01-30  15.1
...          ...   ...
3620  1990-12-02  13.2
3621  1990-12-03  16.2
3622  1990-12-04  17.3
3623  1990-12-05  20.5
3624  1990-12-06  20.2
3625  1990-12-07  19.4
3626  1990-12-08  15.5
3627  1990-12-09  14.1
3628  1990-12-10  11.0
3629  1990-12-11  11.1
3630  1990-12-12  14.0
3631  1990-12-13  11.4
3632  1990-12-14  12.5
3633  1990-12-15  13.4
3634  1990-12-16  13.6
3635  1990-12-17  13.9
3636  1990-12-18  17.2
3637  1990-12-19  14.7
3638  1990-12-20  15.4
3639  1990-12-21  13.1
3640  1990-12-22  13.2
3641  1990-12-23  13.9
3642  1990-12-24  10.0
3643  1990-12-25  12.9
3644  1990-12-26  14.6
3645  1990-12-27  14.0
3646  1990-12-28  13.6
3647  1990-12-29  13.5
3648  1990-12-30  15.7
3649  1990-12-31  13.0

[3650 rows x 2 columns]

# Create a time series model from scratch